/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CusAsk: typeof import('./src/components/CusAsk/index.vue')['default']
    CusEmpty: typeof import('./src/components/CusEmpty/index.vue')['default']
    CusLang: typeof import('./src/components/CusLang/index.vue')['default']
    CusLoading: typeof import('./src/components/CusLoading/index.vue')['default']
    CusNav: typeof import('./src/components/CusNav/index.vue')['default']
    CusNumber: typeof import('./src/components/CusNumber/index.vue')['default']
    CusPaytype: typeof import('./src/components/CusPaytype/index.vue')['default']
    CusPicker: typeof import('./src/components/CusPicker/index.vue')['default']
    CusProgress: typeof import('./src/components/CusProgress/index.vue')['default']
    CusSms: typeof import('./src/components/CusSms/index.vue')['default']
    CusTab: typeof import('./src/components/CusTab/index.vue')['default']
    CusTitle: typeof import('./src/components/CusTitle/index.vue')['default']
    Pay: typeof import('./src/components/CusPaytype/pay.vue')['default']
    QRCode: typeof import('vue-amazing-ui')['QRCode']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
