/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CusData: typeof import('./src/components/CusData/index.vue')['default']
    CusEmpty: typeof import('./src/components/CusEmpty/index.vue')['default']
    CusLang: typeof import('./src/components/CusLang/index.vue')['default']
    CusLoading: typeof import('./src/components/CusLoading/index.vue')['default']
    CusNav: typeof import('./src/components/CusNav/index.vue')['default']
    CusNumber: typeof import('./src/components/CusNumber/index.vue')['default']
    CusPicker: typeof import('./src/components/CusPicker/index.vue')['default']
    CusSms: typeof import('./src/components/CusSms/index.vue')['default']
    Demo: typeof import('./src/components/CusPicker/demo.vue')['default']
    Picker: typeof import('./src/components/CusPicker/Picker.vue')['default']
    Plasma: typeof import('./src/components/Plasma.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
