export const NODE_INTRO_LOCALES = ['en', 'ko', 'ja', 'ru', 'hi', 'ma', 'id', 'vi', 'hk', 'zh'] as const

type NodeIntroLocale = (typeof NODE_INTRO_LOCALES)[number]
type Section = { heading: string; paragraphs?: string[]; items?: string[] }
type Intro = { title: string; sections: Section[] }
type NodeIntroPair = readonly [visa: Intro, aiPhone: Intro]

const renderIntro = ({ title, sections }: Intro): string => `<section><h3>${title}</h3>${sections.map(({ heading, paragraphs = [], items = [] }) => `<h4>${heading}</h4>${paragraphs.map((text) => `<p>${text}</p>`).join('')}${items.length ? `<ol>${items.map((text) => `<li>${text}</li>`).join('')}</ol>` : ''}`).join('')}</section>`

const zh: NodeIntroPair = [
  {
    title: 'Visa卡业务分红节点',
    sections: [
      { heading: '一、Visa公司基础简介', paragraphs: ['Visa Inc.（维萨）是全球顶尖的数字支付技术企业，总部位于美国加利福尼亚州旧金山市，前身源自1958年的BankAmericard，1976年正式启用Visa品牌，于纽交所上市（股票代码：V）。', 'Visa搭建了全球领先的VisaNet支付网络，业务覆盖200多个国家及地区，每秒可处理数万笔交易，连接消费者、商户、金融机构与政府机构，构建安全、高效的全球支付基础设施。', '本Visa卡合作发行方为新加坡持牌主要支付机构（MPI），由新加坡金融管理局（MAS）监管，符合新加坡《支付服务法》，具备跨境支付、发卡和结算资质。卡片依托Visa主网络，可在全球Visa商户、ATM及线上平台使用，支持多币种支付、即时结算及链上资产与法币兑换。'] },
      { heading: '二、节点分红整体机制', paragraphs: ['分红池来自XSmartPay系统Visa卡全球销售额收益的10%，拆分为100个等额节点；每个节点对应整体分红池1%的长期分红权益。'], items: ['<strong>质押节点：</strong>质押50,000枚AIX，锁仓180天。锁仓期间持续享有对应1%节点分红；期满赎回后权益同步终止，继续质押则权益持续有效。', '<strong>USDT永久买断：</strong>一次性支付12,000 USDT，永久持有一个节点及1%分红权益，无需后续质押或续投。若截至2026年12月31日累计分红未达到12,000 USDT本金，平台补足差额。', '<strong>发放规则：</strong>资金来自Visa卡全球消费交易手续费及相关营收的10%总池，按周期自动结算，可在官方DApp/钱包查看、提取并链上核验。节点总量仅100个。'] },
      { heading: '三、核心说明与风险提示', items: ['Visa主体不直接运营本次节点分红项目；该机制属于合作发行生态激励，与Visa卡基础支付功能相互独立。', 'AIX质押模式存在代币价格波动风险，用户须充分了解加密资产风险。', '保本承诺仅适用于12,000 USDT买断节点，以平台官方合约或公告为准。', '生态面向海外合规用户，并遵循新加坡及相应地区监管规则。'] },
    ],
  },
  {
    title: 'AI量化手机节点',
    sections: [
      { heading: '一、产品核心定位', paragraphs: ['该AI量化手机由新加坡XSmartPay打造、荣耀ODM原厂代工，并由香港AIGT人工智能研究院独家提供技术，是面向全球投资人群的软硬件一体化金融终端。项目拥有十万精准金融会员基础，搭载获微软、OpenAI合计3,500万美元战略投资支持的OpenClaw量化引擎，一台设备兼具交易算力与全球销售额分红价值。'] },
      { heading: '二、硬件与技术优势', items: ['<strong>旗舰代工品质：</strong>荣耀全链路ODM生产，完成金融级安全调校，支持7×24小时量化运算；续航、散热适合长期挂机，并配套量化平板等终端。', '<strong>量化算法底座：</strong>香港AIGT研究院自研OpenClaw引擎，经全球海量行情训练，可自动捕捉跨市场价差，无需专业交易能力或人工盯盘。', '<strong>全域市场覆盖：</strong>原生兼容币安、Polymarket和美股通道，后续将开放A股接口，覆盖加密资产、海外股指及境内A股。', '<strong>销售体系：</strong>覆盖会员分销、线下大宗批发及企业定制；12个月目标出货100万台，单机测算净利润443.1美元。'] },
      { heading: '三、全球节点分红机制', paragraphs: ['项目将AI量化手机全球全部销售额的10%设为分红池，整体分红池对应12,000 USDT基准体量，全球限量开放100个核心节点；每个节点长期分得整机全球销售额的1%，席位发完不再新增。'] },
      { heading: '四、两套官方认购路径', items: ['<strong>AIX质押：</strong>质押50,000枚AIX并锁仓180天。质押期间持续享有1%全球销售额分红，设备量化收益正常获取；只要不提取或解除质押，资格持续保留，一旦解锁提现，当日永久失去该节点全部分红权限。', '<strong>12,000 USDT终身买断：</strong>一次性全款买断，无期限、无需质押且不退不换，席位永久归认购人。若截至2026年12月31日累计分红未达到2,000 USDT，平台补足收益差额。'] },
      { heading: '五、整机配套落地能力', paragraphs: ['设备销售利润及项目经营资金将投入硬件扩产、全球市场宣传、OpenClaw算法迭代、A股接口开发和专业运维团队，保障业务稳定运转并支撑节点持有者分红。'] },
    ],
  },
]

const hk: NodeIntroPair = [
  { title: 'Visa卡業務分紅節點', sections: [
    { heading: '一、Visa公司基礎簡介', paragraphs: ['Visa Inc.是全球領先的數碼支付技術企業，總部位於美國三藩市，源自1958年的BankAmericard，1976年啟用Visa品牌，於紐交所上市（代碼：V）。VisaNet覆蓋200多個國家和地區，連接消費者、商戶、金融機構及政府。', '合作發卡方為受新加坡金融管理局（MAS）監管的持牌主要支付機構（MPI），符合《支付服務法》。卡片可在全球Visa商戶、ATM及網上平台使用，支援多幣種支付、即時結算及鏈上資產與法幣兌換。'] },
    { heading: '二、節點分紅整體機制', paragraphs: ['分紅池來自XSmartPay系統Visa卡全球銷售額收益的10%，分為100個等額節點，每個節點享有整體分紅池1%的長期權益。'], items: ['<strong>AIX質押：</strong>質押50,000枚AIX並鎖倉180天；質押期間享有分紅，贖回後權益終止。', '<strong>永久買斷：</strong>一次支付12,000 USDT，永久持有1%節點權益。若截至2026年12月31日累計分紅不足12,000 USDT本金，平台補足差額。', '<strong>發放：</strong>從Visa卡交易手續費及相關營收的10%總池定期自動結算，可於DApp/錢包查閱、提取及鏈上核驗；僅限100席。'] },
    { heading: '三、核心說明與風險提示', items: ['Visa主體不直接營運此節點項目；節點激勵與Visa卡基本支付功能獨立。', 'AIX價格可能波動，參與者須了解加密資產風險。', '保本承諾僅適用於12,000 USDT買斷節點，以官方合約或公告為準。', '項目遵守新加坡及參與者所在地的監管規則。'] },
  ] },
  { title: 'AI量化手機節點', sections: [
    { heading: '一、產品核心定位', paragraphs: ['此金融終端由新加坡XSmartPay打造、榮耀ODM原廠代工及香港AIGT人工智能研究院供應技術，擁有十萬金融會員基礎，搭載獲微軟與OpenAI合計3,500萬美元戰略投資支持的OpenClaw量化引擎，兼具交易算力與銷售分紅。'] },
    { heading: '二、硬件與技術優勢', items: ['榮耀全鏈路ODM及金融級安全調校，支援7×24小時運算，並設量化平板系列。', 'AIGT自研OpenClaw可自動捕捉跨市場價差，毋須專業知識或盯盤。', '兼容幣安、Polymarket及美股，日後開放A股接口。', '渠道包括會員分銷、批發及企業訂製；12個月目標100萬台，單機預計淨利443.1美元。'] },
    { heading: '三、全球節點分紅', paragraphs: ['全球銷售額10%進入分紅池，基準體量12,000 USDT；限量100席，每席長期享有全球銷售額1%，發完不增發。'] },
    { heading: '四、認購路徑', items: ['<strong>AIX質押：</strong>質押50,000枚並鎖倉180天，持續質押即保留1%分紅；解除質押當日永久失去該席全部權益。', '<strong>終身買斷：</strong>支付12,000 USDT，不退不換、毋須質押、永久持有。若截至2026年12月31日累計分紅不足2,000 USDT，平台補足差額。'] },
    { heading: '五、落地能力', paragraphs: ['銷售利潤及營運資金將用於產能、全球推廣、OpenClaw迭代、A股接口及專業運維，支撐業務與節點分紅。'] },
  ] },
]

const en: NodeIntroPair = [
  { title: 'Visa Card Business Dividend Node', sections: [
    { heading: '1. About Visa', paragraphs: ['Visa Inc. is a leading digital-payments technology company headquartered in San Francisco. Originating as BankAmericard in 1958, it adopted the Visa brand in 1976 and is listed on the NYSE (V). VisaNet serves more than 200 countries and territories and connects consumers, merchants, financial institutions and governments.', 'The partner issuer is a Singapore-licensed Major Payment Institution (MPI), regulated by MAS under the Payment Services Act. The card uses the Visa network for worldwide merchants, ATMs and online platforms, with multi-currency payments, instant settlement and conversion between on-chain assets and fiat.'] },
    { heading: '2. Dividend mechanism', paragraphs: ['10% of XSmartPay system revenue from global Visa card sales forms a pool split into 100 equal nodes. Each node receives 1% of that pool as a long-term dividend right.'], items: ['<strong>AIX staking:</strong> stake 50,000 AIX for a 180-day lock. The dividend continues while staked and ends when redeemed.', '<strong>Permanent purchase:</strong> pay 12,000 USDT once for permanent 1% node rights. If cumulative dividends are below the 12,000 USDT principal by December 31, 2026, the platform will cover the difference.', '<strong>Distribution:</strong> the pool comes from 10% of Visa card transaction fees and related revenue, settles automatically by cycle, and is viewable, withdrawable and verifiable on-chain through the official DApp/wallet. Supply is capped at 100 nodes.'] },
    { heading: '3. Important notices and risks', items: ['Visa itself does not operate this node program; it is an ecosystem incentive independent of normal Visa card payment functions.', 'AIX staking carries token-price volatility risk.', 'The principal protection applies only to the 12,000 USDT permanent node and is governed by official contracts or announcements.', 'Participation is for compliant overseas users and follows Singapore and applicable local rules.'] },
  ] },
  { title: 'AI Quantitative Phone Node', sections: [
    { heading: '1. Product positioning', paragraphs: ['Built by Singapore-based XSmartPay, manufactured through Honor ODM, and powered exclusively by Hong Kong AIGT AI Research Institute, this integrated financial terminal serves global investors. It starts with 100,000 targeted financial members and uses the OpenClaw engine, backed by a combined US$35 million strategic investment from Microsoft and OpenAI, to deliver both trading compute and sales dividends.'] },
    { heading: '2. Hardware and technology', items: ['Honor full-chain ODM, financial-grade security tuning, 24/7 computation, long-running battery and thermal design, plus quantitative tablets.', 'AIGT-developed OpenClaw uses global market data to identify cross-market spreads automatically without professional skills or manual monitoring.', 'Native access to Binance, Polymarket and US equities, with an A-share interface planned.', 'Member distribution, wholesale and enterprise customization target 1 million units in 12 months, with estimated net profit of US$443.1 per unit.'] },
    { heading: '3. Global node dividends', paragraphs: ['10% of all worldwide phone sales enters a pool with a 12,000 USDT reference size. Only 100 core nodes are offered; each receives 1% of global device sales on a long-term basis and no new seats will be added.'] },
    { heading: '4. Subscription options', items: ['<strong>AIX staking:</strong> stake 50,000 AIX for 180 days. The 1% sales dividend remains while staking; withdrawing or unlocking permanently removes all node dividends that day.', '<strong>Lifetime purchase:</strong> pay 12,000 USDT once. The seat is permanent, requires no staking and is non-refundable/non-exchangeable. If total dividends are below 2,000 USDT by December 31, 2026, the platform will cover the shortfall.'] },
    { heading: '5. Delivery capability', paragraphs: ['Sales profit and operating funds support production expansion, global marketing, OpenClaw upgrades, A-share connectivity and professional operations, sustaining the business and node dividends.'] },
  ] },
]

type LocalizedBody = readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string]

const BODIES: Record<'ko' | 'ja' | 'ru' | 'hi' | 'ma' | 'id' | 'vi', LocalizedBody> = {
  ko: ['XSmartPay Visa 수익의 10%를 100개 노드로 나누며 각 노드는 풀의 1%를 받습니다.', '50,000 AIX를 180일 잠그며 스테이킹 중에만 권리가 유지됩니다.', '12,000 USDT로 영구 1% 권리를 매입합니다. 2026년 12월 31일까지 배당이 원금보다 적으면 플랫폼이 차액을 보전합니다.', '공식 DApp/지갑에서 주기적으로 자동 정산되고 온체인 검증이 가능하며 총 100개로 제한됩니다.', 'Visa 본사는 이 노드 프로그램을 직접 운영하지 않으며 일반 카드 결제 서비스와 별개입니다.', 'AIX에는 암호자산 가격 변동 위험이 있습니다.', '원금 보전은 12,000 USDT 매입에만 적용되며 공식 약관을 따릅니다.', '싱가포르 및 해당 지역의 규정을 준수해야 합니다.', 'XSmartPay, Honor ODM, 홍콩 AIGT가 만든 단말로 10만 금융 회원과 Microsoft·OpenAI 합계 3,500만 달러 지원의 OpenClaw를 기반으로 거래 연산과 판매 배당을 제공합니다.', '금융급 24시간 하드웨어, 자동 차익 탐지, Binance·Polymarket·미국 주식 지원 및 향후 A주 연동을 제공합니다.', '12개월 100만 대, 대당 순이익 443.1달러를 목표로 합니다.', '글로벌 판매액의 10%, 기준 12,000 USDT, 한정 100개 노드이며 각 노드는 판매액 1%를 받습니다.', '50,000 AIX를 180일 잠그며 해제 시 모든 배당 권리를 영구 상실합니다.', '12,000 USDT 종신 매입은 환불·교환이 불가합니다. 2026년 12월 31일까지 배당이 2,000 USDT 미만이면 차액을 보전합니다.', '자금은 생산, 글로벌 마케팅, OpenClaw 고도화, A주 연동과 전문 운영에 사용됩니다.'],
  ja: ['XSmartPayのVisa収益の10%を100ノードに分割し、各ノードはプールの1%を受け取ります。', '50,000 AIXを180日ロックし、ステーキング中のみ権利が継続します。', '12,000 USDTで1%の権利を永久取得します。2026年12月31日までの配当が元本未満の場合、プラットフォームが差額を補填します。', '公式DApp／ウォレットで定期的に自動精算され、オンチェーン検証が可能です。上限は100ノードです。', 'Visa本体は本プログラムを直接運営せず、通常のカード決済機能とは独立しています。', 'AIXには暗号資産の価格変動リスクがあります。', '元本保護は12,000 USDTの買い切りに限られ、公式条件に従います。', 'シンガポールおよび該当地域の規制が適用されます。', 'XSmartPay、Honor ODM、香港AIGTによる端末で、10万人の金融会員基盤とMicrosoft・OpenAI合計3,500万米ドルの支援を受けたOpenClawにより、取引演算と販売配当を提供します。', '金融級の24時間稼働、価格差の自動検出、Binance・Polymarket・米国株への対応、将来のA株接続を備えます。', '12か月で100万台、1台当たり純利益443.1米ドルを計画しています。', '世界販売額の10%、基準12,000 USDT、限定100ノードで、各ノードは販売額の1%を受け取ります。', '50,000 AIXを180日ロックし、解除すると全配当権を永久に失います。', '12,000 USDTの終身買い切りは返金・交換不可です。2026年12月31日までの配当が2,000 USDT未満なら差額を補填します。', '資金は生産、世界展開、OpenClaw改良、A株接続、専門運営に使用されます。'],
  ru: ['10% дохода XSmartPay от Visa делятся между 100 узлами; каждый получает 1% пула.', 'Стейкинг 50 000 AIX на 180 дней; права действуют только во время стейкинга.', '12 000 USDT дают бессрочное право на 1%. Если к 31 декабря 2026 года дивиденды ниже основной суммы, платформа покрывает разницу.', 'Периодический автоматический расчёт через официальный DApp/кошелёк с проверкой в блокчейне; максимум 100 узлов.', 'Visa не управляет программой напрямую; она независима от обычных карточных услуг.', 'AIX подвержен ценовой волатильности криптоактивов.', 'Защита капитала действует только для покупки за 12 000 USDT и регулируется официальными условиями.', 'Применяются нормы Сингапура и соответствующей юрисдикции.', 'Терминал XSmartPay, Honor ODM и AIGT опирается на 100 000 финансовых участников и OpenClaw, поддержанный Microsoft и OpenAI на 35 млн долларов, объединяя вычисления и дивиденды.', 'Финансовое оборудование 24/7, автоматический поиск спредов, Binance, Polymarket, акции США и будущий доступ к A-акциям.', 'Цель на 12 месяцев — 1 млн устройств; расчётная чистая прибыль — 443,1 доллара с устройства.', '10% глобальных продаж, база 12 000 USDT, 100 узлов; каждый получает 1% продаж.', 'Стейкинг 50 000 AIX на 180 дней; разблокировка навсегда прекращает все дивиденды.', 'Бессрочная покупка за 12 000 USDT не возвращается и не обменивается. Если к 31 декабря 2026 года дивиденды ниже 2 000 USDT, разница покрывается.', 'Средства направляются на производство, мировой маркетинг, OpenClaw, доступ к A-акциям и операционную команду.'],
  hi: ['XSmartPay Visa आय का 10% 100 नोड में बाँटा जाता है; हर नोड पूल का 1% पाता है।', '50,000 AIX को 180 दिन लॉक करें; अधिकार केवल स्टेकिंग जारी रहने तक रहता है।', '12,000 USDT में स्थायी 1% अधिकार मिलता है। 31 दिसंबर 2026 तक लाभांश मूलधन से कम होने पर प्लेटफ़ॉर्म अंतर पूरा करेगा।', 'आधिकारिक DApp/वॉलेट से आवधिक स्वचालित निपटान और ऑन-चेन सत्यापन; अधिकतम 100 नोड।', 'Visa स्वयं यह नोड कार्यक्रम नहीं चलाता; यह सामान्य कार्ड भुगतान सेवा से अलग है।', 'AIX में क्रिप्टो मूल्य उतार-चढ़ाव का जोखिम है।', 'मूलधन सुरक्षा केवल 12,000 USDT खरीद पर और आधिकारिक शर्तों के अनुसार लागू है।', 'सिंगापुर और संबंधित स्थानीय नियम लागू होते हैं।', 'XSmartPay, Honor ODM और Hong Kong AIGT का टर्मिनल 100,000 वित्तीय सदस्यों तथा Microsoft और OpenAI के संयुक्त 35 मिलियन डॉलर समर्थित OpenClaw से ट्रेडिंग कंप्यूट और बिक्री लाभांश देता है।', 'वित्तीय-ग्रेड 24/7 हार्डवेयर, स्वचालित अंतर पहचान, Binance, Polymarket, अमेरिकी शेयर और नियोजित A-share पहुँच।', '12 महीने में 10 लाख यूनिट तथा प्रति यूनिट 443.1 डॉलर अनुमानित शुद्ध लाभ का लक्ष्य।', 'वैश्विक बिक्री का 10%, 12,000 USDT आधार, सीमित 100 नोड; प्रत्येक को बिक्री का 1%।', '50,000 AIX को 180 दिन लॉक करें; अनलॉक करने पर सभी लाभांश अधिकार स्थायी रूप से समाप्त।', '12,000 USDT की आजीवन खरीद वापस या बदली नहीं जा सकती। 31 दिसंबर 2026 तक लाभांश 2,000 USDT से कम हो तो अंतर पूरा होगा।', 'धन उत्पादन, वैश्विक विपणन, OpenClaw सुधार, A-share पहुँच और पेशेवर संचालन में लगाया जाएगा।'],
  ma: ['10% hasil Visa XSmartPay dibahagi kepada 100 nod; setiap nod menerima 1% daripada dana.', 'Stake 50,000 AIX selama 180 hari; hak kekal hanya semasa staking.', 'Bayar 12,000 USDT untuk hak 1% kekal. Jika dividen belum mencapai prinsipal pada 31 Disember 2026, platform menampung perbezaan.', 'Penyelesaian automatik berkala melalui DApp/dompet rasmi, boleh disahkan pada rantaian; maksimum 100 nod.', 'Visa tidak mengendalikan program nod ini secara langsung; ia berasingan daripada fungsi pembayaran kad biasa.', 'AIX mempunyai risiko turun naik harga aset kripto.', 'Perlindungan prinsipal hanya untuk pembelian 12,000 USDT dan tertakluk pada terma rasmi.', 'Peraturan Singapura dan tempatan yang berkaitan terpakai.', 'Terminal XSmartPay, Honor ODM dan AIGT menggunakan asas 100,000 ahli serta OpenClaw yang disokong pelaburan gabungan AS$35 juta Microsoft dan OpenAI untuk pengiraan dagangan dan dividen jualan.', 'Perkakasan gred kewangan 24/7, pengesanan spread automatik, Binance, Polymarket, saham AS dan akses saham A yang dirancang.', 'Sasaran 12 bulan ialah 1 juta unit dengan anggaran untung bersih AS$443.1 seunit.', '10% jualan global, asas 12,000 USDT, 100 nod terhad; setiap nod menerima 1% jualan.', 'Stake 50,000 AIX selama 180 hari; membuka kunci menamatkan semua hak dividen secara kekal.', 'Pembelian seumur hidup 12,000 USDT tidak boleh dipulang atau ditukar. Jika dividen di bawah 2,000 USDT pada 31 Disember 2026, perbezaan ditampung.', 'Dana menyokong kapasiti, pemasaran global, peningkatan OpenClaw, akses saham A dan operasi profesional.'],
  id: ['10% pendapatan Visa XSmartPay dibagi menjadi 100 node; setiap node menerima 1% dari kumpulan.', 'Stake 50.000 AIX selama 180 hari; hak berlaku hanya selama staking.', 'Bayar 12.000 USDT untuk hak 1% permanen. Jika dividen belum mencapai pokok pada 31 Desember 2026, platform menutup selisihnya.', 'Penyelesaian otomatis berkala melalui DApp/dompet resmi dan dapat diverifikasi on-chain; maksimum 100 node.', 'Visa tidak mengoperasikan program node ini secara langsung; program terpisah dari layanan pembayaran kartu biasa.', 'AIX memiliki risiko volatilitas harga aset kripto.', 'Perlindungan pokok hanya untuk pembelian 12.000 USDT dan mengikuti ketentuan resmi.', 'Aturan Singapura dan wilayah terkait berlaku.', 'Terminal XSmartPay, Honor ODM dan AIGT memakai basis 100.000 anggota serta OpenClaw yang didukung investasi gabungan US$35 juta dari Microsoft dan OpenAI untuk komputasi perdagangan dan dividen penjualan.', 'Perangkat finansial 24/7, deteksi spread otomatis, Binance, Polymarket, saham AS dan akses saham A yang direncanakan.', 'Target 12 bulan 1 juta unit dengan estimasi laba bersih US$443,1 per unit.', '10% penjualan global, basis 12.000 USDT, 100 node terbatas; setiap node menerima 1% penjualan.', 'Stake 50.000 AIX selama 180 hari; membuka kunci mengakhiri seluruh hak dividen secara permanen.', 'Pembelian seumur hidup 12.000 USDT tidak dapat dikembalikan atau ditukar. Jika dividen di bawah 2.000 USDT pada 31 Desember 2026, selisih ditutup.', 'Dana mendukung kapasitas, pemasaran global, peningkatan OpenClaw, akses saham A dan operasi profesional.'],
  vi: ['10% doanh thu Visa của XSmartPay được chia thành 100 nút; mỗi nút nhận 1% quỹ.', 'Khóa 50.000 AIX trong 180 ngày; quyền chỉ duy trì khi còn đặt cọc.', 'Trả 12.000 USDT để sở hữu vĩnh viễn quyền 1%. Nếu đến 31/12/2026 cổ tức chưa đạt vốn gốc, nền tảng bù phần chênh lệch.', 'Tự động quyết toán định kỳ qua DApp/ví chính thức, có thể xác minh on-chain; tối đa 100 nút.', 'Visa không trực tiếp vận hành chương trình nút; chương trình độc lập với dịch vụ thanh toán thẻ thông thường.', 'AIX có rủi ro biến động giá tài sản mã hóa.', 'Bảo vệ vốn chỉ áp dụng cho gói mua 12.000 USDT và theo điều khoản chính thức.', 'Áp dụng quy định Singapore và địa phương liên quan.', 'Thiết bị của XSmartPay, Honor ODM và AIGT dựa trên 100.000 thành viên cùng OpenClaw được Microsoft và OpenAI hỗ trợ tổng cộng 35 triệu USD, kết hợp năng lực giao dịch và cổ tức bán hàng.', 'Phần cứng tài chính 24/7, tự động tìm chênh lệch, hỗ trợ Binance, Polymarket, cổ phiếu Mỹ và dự kiến kết nối cổ phiếu A.', 'Mục tiêu 12 tháng là 1 triệu máy, lợi nhuận ròng ước tính 443,1 USD mỗi máy.', '10% doanh số toàn cầu, quy mô tham chiếu 12.000 USDT, giới hạn 100 nút; mỗi nút nhận 1% doanh số.', 'Khóa 50.000 AIX trong 180 ngày; mở khóa sẽ chấm dứt vĩnh viễn mọi quyền cổ tức.', 'Mua trọn đời 12.000 USDT không hoàn trả hoặc đổi. Nếu đến 31/12/2026 cổ tức dưới 2.000 USDT, nền tảng bù chênh lệch.', 'Nguồn vốn dùng cho sản xuất, tiếp thị toàn cầu, nâng cấp OpenClaw, kết nối cổ phiếu A và vận hành chuyên nghiệp.'],
}

const localized = (locale: keyof typeof BODIES, visaTitle: string, aiTitle: string, labels: readonly [string, string, string, string, string, string, string, string, string, string, string, string]): NodeIntroPair => {
  const [about, visaAbout, mechanism, stake, buy, distribute, risks, product, tech, dividend, options, delivery] = labels
  const b = BODIES[locale]
  return [
    { title: visaTitle, sections: [
      { heading: about, paragraphs: [visaAbout] },
      { heading: mechanism, paragraphs: [b[0]], items: [`<strong>${stake}:</strong> ${b[1]}`, `<strong>${buy}:</strong> ${b[2]}`, `<strong>${distribute}:</strong> ${b[3]}`] },
      { heading: risks, items: [b[4], b[5], b[6], b[7]] },
    ] },
    { title: aiTitle, sections: [
      { heading: product, paragraphs: [b[8]] },
      { heading: tech, items: [b[9], b[10]] },
      { heading: dividend, paragraphs: [b[11]] },
      { heading: options, items: [`<strong>${stake}:</strong> ${b[12]}`, `<strong>${buy}:</strong> ${b[13]}`] },
      { heading: delivery, paragraphs: [b[14]] },
    ] },
  ]
}

const ko = localized('ko', 'Visa 카드 사업 배당 노드', 'AI 퀀트폰 노드', ['1. Visa 소개', 'Visa Inc.는 1958년 BankAmericard에서 시작해 1976년 Visa 브랜드를 채택한 글로벌 결제 기업입니다. VisaNet은 200여 국가와 지역을 연결하며, 발급사는 MAS의 감독을 받는 싱가포르 MPI입니다.', '2. 배당 구조', 'AIX 스테이킹', '영구 매입', '지급', '3. 핵심 안내 및 위험', '1. 제품 포지셔닝', '2. 하드웨어와 기술', '3. 글로벌 노드 배당', '4. 공식 참여 방식', '5. 사업 실행 역량'])
const ja = localized('ja', 'Visaカード事業配当ノード', 'AIクオンツスマートフォンノード', ['1. Visaの概要', 'Visa Inc.は1958年のBankAmericardを起源とし、1976年にVisaブランドを採用した世界的決済企業です。VisaNetは200以上の国・地域を結び、提携発行会社はMAS監督下のシンガポールMPIです。', '2. 配当制度', 'AIXステーキング', '永久買い切り', '配当', '3. 重要事項とリスク', '1. 製品の位置付け', '2. ハードウェアと技術', '3. グローバルノード配当', '4. 公式参加方法', '5. 事業遂行能力'])
const ru = localized('ru', 'Дивидендный узел карточного бизнеса Visa', 'Узел телефона для ИИ-квант-трейдинга', ['1. О Visa', 'Visa Inc. — глобальная платёжная компания, происходящая от BankAmericard (1958) и использующая бренд Visa с 1976 года. VisaNet охватывает более 200 стран и территорий; партнёр-эмитент — сингапурская MPI под надзором MAS.', '2. Механизм дивидендов', 'Стейкинг AIX', 'Бессрочная покупка', 'Выплата', '3. Условия и риски', '1. Назначение продукта', '2. Оборудование и технологии', '3. Глобальные дивиденды', '4. Способы участия', '5. Реализация проекта'])
const hi = localized('hi', 'Visa कार्ड व्यवसाय लाभांश नोड', 'AI क्वांट फोन नोड', ['1. Visa परिचय', 'Visa Inc. एक वैश्विक डिजिटल भुगतान कंपनी है, जिसकी शुरुआत 1958 के BankAmericard से हुई और जिसने 1976 में Visa नाम अपनाया। VisaNet 200 से अधिक देशों/क्षेत्रों में है; साझेदार जारीकर्ता MAS-विनियमित सिंगापुर MPI है।', '2. लाभांश व्यवस्था', 'AIX स्टेकिंग', 'स्थायी खरीद', 'वितरण', '3. मुख्य सूचना और जोखिम', '1. उत्पाद स्थिति', '2. हार्डवेयर और तकनीक', '3. वैश्विक नोड लाभांश', '4. आधिकारिक भागीदारी', '5. कार्यान्वयन क्षमता'])
const ma = localized('ma', 'Nod Dividen Perniagaan Kad Visa', 'Nod Telefon Kuantitatif AI', ['1. Pengenalan Visa', 'Visa Inc. ialah syarikat pembayaran digital global yang bermula sebagai BankAmericard pada 1958 dan menggunakan jenama Visa sejak 1976. VisaNet meliputi lebih 200 negara dan wilayah; penerbit rakan ialah MPI Singapura yang diselia MAS.', '2. Mekanisme dividen', 'Staking AIX', 'Pembelian kekal', 'Agihan', '3. Maklumat dan risiko', '1. Kedudukan produk', '2. Perkakasan dan teknologi', '3. Dividen nod global', '4. Pilihan rasmi', '5. Keupayaan pelaksanaan'])
const id = localized('id', 'Node Dividen Bisnis Kartu Visa', 'Node Ponsel Kuantitatif AI', ['1. Tentang Visa', 'Visa Inc. adalah perusahaan pembayaran digital global yang bermula dari BankAmericard pada 1958 dan memakai merek Visa sejak 1976. VisaNet menjangkau lebih dari 200 negara dan wilayah; penerbit mitra adalah MPI Singapura di bawah MAS.', '2. Mekanisme dividen', 'Staking AIX', 'Pembelian permanen', 'Distribusi', '3. Informasi dan risiko', '1. Posisi produk', '2. Perangkat keras dan teknologi', '3. Dividen node global', '4. Jalur partisipasi', '5. Kemampuan pelaksanaan'])
const vi = localized('vi', 'Nút chia cổ tức kinh doanh thẻ Visa', 'Nút điện thoại định lượng AI', ['1. Giới thiệu Visa', 'Visa Inc. là doanh nghiệp thanh toán số toàn cầu, bắt nguồn từ BankAmericard năm 1958 và dùng thương hiệu Visa từ năm 1976. VisaNet phủ hơn 200 quốc gia và vùng lãnh thổ; đơn vị phát hành đối tác là MPI Singapore do MAS giám sát.', '2. Cơ chế cổ tức', 'Đặt cọc AIX', 'Mua vĩnh viễn', 'Phân phối', '3. Thông tin và rủi ro', '1. Định vị sản phẩm', '2. Phần cứng và công nghệ', '3. Cổ tức nút toàn cầu', '4. Phương thức tham gia', '5. Năng lực triển khai'])

const NODE_INTROS: Record<NodeIntroLocale, NodeIntroPair> = { en, ko, ja, ru, hi, ma, id, vi, hk, zh }

const isNodeIntroLocale = (locale: string): locale is NodeIntroLocale => NODE_INTRO_LOCALES.includes(locale as NodeIntroLocale)

export const getNodeIntro = (locale: string, nodeIndex: number): string => {
  if (nodeIndex !== 0 && nodeIndex !== 1) return ''
  const resolvedLocale = isNodeIntroLocale(locale) ? locale : 'zh'
  return renderIntro(NODE_INTROS[resolvedLocale][nodeIndex])
}
